def require_tool(tool):
  # tool = shlex.quote(tool)
  local_resource(
    'ensure-deps',
      cmd="""
      if ! command -v {tool} >/dev/null 2>&1; then
        echo >&2 "{tool} is required but was not found in PATH"
        exit 1
      fi
      """.format(
        tool=tool
      ),
      # `cmd_bat`, when present, is used instead of `cmd` on Windows.
      cmd_bat=[
          "powershell.exe",
          "-Noninteractive",
          "-Command",
          '& {{if (!(Get-Command {tool} -ErrorAction SilentlyContinue)) {{ Write-Error "{tool} is required but was not found in PATH"; exit 1 }}}}'.format(
              tool=tool
          ),
      ],
  )

def expand_service_yaml(name):
  watch_file(name)
  return local('envsubst < {}'.format(name))

# Don't hide mock secrets in Tilt log output.
secret_settings (
  disable_scrub = True
)

def make_env():
  # Set some reasonable values for development; these will be injected into the service.yaml
  # when it gets processed by expand_service_yaml().
  # We use existing values if already set (i.e. in CI); otherwise set development defaults.
  env_name_long = os.getenv("ENV_NAME_LONG", default = "local")
  registry_slash = os.getenv("REGISTRY_SLASH", "")
  version = os.getenv("VERSION", default = "local") # In CI, this is the git commit or tag

  os.putenv("DD_TRACE_ENABLED", "false")
  os.putenv("LOG_LEVEL", "DEBUG")
  os.putenv("VERSION", version)
  os.putenv("ENV_NAME_LONG", env_name_long)
  os.putenv("REGISTRY_SLASH", registry_slash)
  os.putenv("VERSION_SHORT", version[0:20])
